version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  account:
    build:
      context: ./account
      target: builder
    image: account
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`localhost`) && PathPrefix(`/api/account`)"
      - "traefik.http.services.account.loadbalancer.server.port=8080"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
